//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyPay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration
    {
        public int ID { get; set; }
        public string IntacctURL { get; set; }
        public string IntacctCompanyID { get; set; }
        public string IntacctUserName { get; set; }
        public string IntacctPassword { get; set; }
        public string IntacctSenderID { get; set; }
        public string IntacctSenderPassword { get; set; }
        public string JournalURL { get; set; }
        public string KeyPayAPI { get; set; }
        public string BusinessID { get; set; }
        public string Journal { get; set; }
        public string PostingMode { get; set; }
        public string LogFiles { get; set; }
        public string FromEmail { get; set; }
        public string EmailPassword { get; set; }
        public string SMTPServer { get; set; }
        public string EmailPort { get; set; }
        public string SSL { get; set; }
        public string ToEmail { get; set; }
        public string CCEmail { get; set; }
    }
}
