//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyPay.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Configuration
    {
        public int ID { get; set; }
        [Required]
        public string IntacctURL { get; set; }
        [Required]
        public string IntacctCompanyID { get; set; }
        [Required]
        public byte[] IntacctUserName { get; set; }
        [NotMapped]
        public string strIntacctUserName { get; set; }
        [Required]
        public byte[] IntacctPassword { get; set; }
        [NotMapped]
        public string strIntacctPassword { get; set; }
        [Required]
        public string IntacctSenderID { get; set; }
        [Required]
        public byte[] IntacctSenderPassword { get; set; }
        [NotMapped]
        public string strIntacctSenderPassword { get; set; }
        [Required]
        public string JournalURL { get; set; }
        [Required]
        public byte[] KeyPayAPI { get; set; }
        [NotMapped]
        public string strKeyPayAPI { get; set; }
        [Required]
        public string BusinessID { get; set; }
        [Required]
        public string Journal { get; set; }
        [Required]
        public string PostingMode { get; set; }
        [Required]
        public string LogFiles { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        public string FromEmail { get; set; }
        [Required]
        public byte[] EmailPassword { get; set; }
        [NotMapped]
        public string strEmailPassword { get; set; }
        [Required]
        public string SMTPServer { get; set; }
        [Required]
        public string EmailPort { get; set; }
        [Required]
        public bool SSL { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        public string ToEmail { get; set; }
        [DataType(DataType.EmailAddress)]
        public string CCEmail { get; set; }
        public int Department { get; set; }
        public int Location { get; set; }
        public int Project { get; set; }
    }

    public enum PostingModes
    {
        Draft,
        Posted
    }

}
