//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyPay.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class User
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "User Name required.")]
        //[DataType(DataType.EmailAddress)]
        [RegularExpression(@"^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$", ErrorMessage = "User name is invalid.")]
        public string UserName { get; set; }

        //[Required]
        //[DataType(DataType.Password)]
        public byte[] Password { get; set; }

        [NotMapped]
        [Required(ErrorMessage = "The Password field is required.")]
        [DataType(DataType.Password)]
        public string strPassword { get; set; }

        [NotMapped]
        [Required(ErrorMessage = "The Confirm Password field is required.")]
        [DataType(DataType.Password)]
        [Compare("strPassword", ErrorMessage = "Password does not match!")]
        public string ConfirmPassword { get; set; }


    }
}
